default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails
  password: rails
  host: localhost
  port: 5432

development:
  <<: *default
  database: online_exam_dev

# test:
#   <<: *default
#   database: teacher_test

production:
  <<: *default
  database: online_exam_prod